"""The model-facing tool set, written for an agent helping an iOS user.

House style for every description: **what it does, then when to use it.**  One or two
sentences, no restating the parameter schema (the model already has that) and no
marketing.  A description that says "use this when the user asks for X" is worth more
than one that says "this tool is a powerful utility for X".

The file tools share a :class:`Workspace` path jail, so ``../../etc/passwd`` is refused
before it reaches the filesystem.  Everything here is synchronous on purpose: the
registry runs sync handlers in a worker thread, which is what makes a batch of tool
calls overlap instead of queueing behind the slowest one.
"""

from __future__ import annotations

import fnmatch
import io
import json
import os
import re
import runpy
import shutil
import shlex
import signal
import subprocess
import sys
import threading
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple

from . import budget, custom_tools, doctor, ios, module_tools, pyto_api, repair, unix_tools
from .config import Config, ConfigError, load_config
from .errors import ToolError
from .home import expand_user_path
from .security import (
    chmod_private as security_chmod,
    mkdir_private,
    open_private,
    scrub_secrets,
    scrubbed_environ,
    temporary_environ_scrub,
    write_private,
)
from .tools import ToolDef, ToolRegistry, ToolResult

#: Never read more than this into the conversation from one file.
MAX_READ_CHARS = 60000
#: Default cap on ``search_files`` matches, and the hard ceiling on that cap.
DEFAULT_SEARCH_LIMIT = 50
MAX_SEARCH_LIMIT = 500
#: Files larger than this are skipped by the searcher (they are never a note).
MAX_SEARCH_FILE_BYTES = 2_000_000
#: stdout/stderr kept in the tool result; the rest goes to a capture file.
RUN_CAPTURE_CHARS = 20000
#: Per-stream byte ceiling for a subprocess, to stop a runaway print loop.
RUN_CAPTURE_BYTES = 512 * 1024
DEFAULT_RUN_TIMEOUT = 30.0
MAX_RUN_TIMEOUT = 300.0
#: Ceiling on one ``pyto_api`` answer.  Big enough for any single module's reference, small
#: enough that it never crowds the conversation.
MAX_PYTO_REFERENCE_CHARS = 8000

SKIP_DIRS = frozenset(
    {
        ".git",
        ".hg",
        ".svn",
        "__pycache__",
        "node_modules",
        ".venv",
        "venv",
        ".mypy_cache",
        ".pytest_cache",
        "tool-output",
        ".Trash",
    }
)

PROGRAM_HEADER = "# Generated by pyto-harness for {purpose}\n# Runs on iOS with Pyto (CPython {version}, standard library only).\n"


# --------------------------------------------------------------------------------------
# Workspace path jail
# --------------------------------------------------------------------------------------


class Workspace:
    """A directory that all file tools are confined to.

    The jail is enforced on the *resolved* path (``realpath``), so ``link/../../x`` and
    a symlink pointing outside the workspace are both caught before any I/O happens.
    """

    def __init__(self, root: str) -> None:
        # The same rule as every user-supplied path: a ``~`` is expanded or refused, so a
        # device without a home directory never gets a workspace literally named ``~``.
        self.root = expand_user_path(root, what="workspace")
        # 0700: the workspace holds the user's programs, the memory store and every spill
        # file (the complete output the model was not shown).  Created private, not
        # chmod'ed later.
        mkdir_private(self.root)

    def resolve(self, relative: str, *, must_exist: bool = False) -> str:
        """Map a model-supplied path to an absolute path inside the workspace."""
        raw = (relative or "").strip()
        if not raw:
            raise ToolError("a path is required")
        if "\x00" in raw:
            raise ToolError("the path contains a NUL byte")
        candidate = raw if os.path.isabs(raw) else os.path.join(self.root, raw)
        resolved = os.path.realpath(candidate)
        root = os.path.realpath(self.root)
        if resolved != root and not resolved.startswith(root + os.sep):
            raise ToolError(
                "refusing to touch {!r}: it resolves to {}, outside the workspace {}".format(
                    raw, resolved, root
                )
            )
        if must_exist and not os.path.exists(resolved):
            raise ToolError("no such file inside the workspace: {}".format(raw))
        return resolved

    def relative(self, absolute: str) -> str:
        try:
            return os.path.relpath(absolute, os.path.realpath(self.root))
        except ValueError:  # pragma: no cover - different drive on Windows
            return absolute


# --------------------------------------------------------------------------------------
# Tool context
# --------------------------------------------------------------------------------------


@dataclass
class ToolContext:
    """Everything the tools need that is not an argument from the model."""

    workspace: Workspace
    spill_dir: str
    #: Set by ``finish``.
    finished: bool = False
    finish_message: str = ""
    #: Persistent user facts, loaded from ``memory.json`` in the workspace.
    memory_path: str = ""
    #: Names of the tools that were called, in order (diagnostics for the UI).
    calls: List[str] = field(default_factory=list)
    #: Test seam: counts how many times ``run_program`` happened, for E2E assertions.
    runs: int = 0
    #: Resolved configuration, when the CLI has one (the self-repair tools need it).
    config: Any = None
    #: Absolute path of the config file the doctor should inspect.
    config_path: str = ""
    #: Where health.json, capabilities.json and backups live.
    state_dir: str = ""
    #: Directory containing run.py and harness/ (the self-repair path jail root).
    harness_root: str = ""
    #: Gate every self-edit on the whole test suite instead of the covering subset.
    full_gate: bool = False
    #: The live registry is used only for explicit custom-tool enable/create operations.
    registry: Optional[ToolRegistry] = None
    #: Lazy, per-process cache of this Pyto build's command inventory.
    unix_inventory: Optional[Dict[str, Any]] = None
    #: Invalid custom tool manifests are reported to the agent but never executed.
    custom_tool_errors: List[str] = field(default_factory=list)

    def note_call(self, name: str) -> None:
        self.calls.append(name)


# --------------------------------------------------------------------------------------
# File tools
# --------------------------------------------------------------------------------------


def _read_text(path: str) -> Tuple[str, bool]:
    """Read a text file, returning ``(text, was_truncated)``.  Binary noise is refused."""
    size = os.path.getsize(path)
    with open(path, "rb") as handle:
        raw = handle.read(MAX_READ_CHARS * 4)
    if b"\x00" in raw[:4096]:
        raise ToolError("{} looks like a binary file; read_file only handles text".format(os.path.basename(path)))
    text = raw.decode("utf-8", "replace")
    if len(text) > MAX_READ_CHARS:
        return text[:MAX_READ_CHARS], True
    if size > len(raw):
        return text, True
    return text, False


def _iter_workspace_files(root: str, pattern: str = "*", limit: int = 5000) -> List[str]:
    """Walk the workspace deterministically, skipping the usual noise directories."""
    matches: List[str] = []
    for current, dirs, files in os.walk(root):
        dirs[:] = sorted(d for d in dirs if d not in SKIP_DIRS and not d.startswith("."))
        for name in sorted(files):
            if pattern in ("*", "") or fnmatch.fnmatch(name, pattern):
                matches.append(os.path.join(current, name))
                if len(matches) >= limit:
                    return matches
    return matches


def build_registry(context: ToolContext) -> ToolRegistry:
    """Create the registry containing every model-facing tool."""
    registry = ToolRegistry()
    context.registry = registry
    workspace = context.workspace

    def protect_custom_tool_store(target: str) -> None:
        relative = workspace.relative(os.path.realpath(target))
        first = relative.split(os.sep, 1)[0]
        if first == custom_tools.STORE_DIR:
            raise ToolError("custom tool files are managed by custom_tool_create/enable/disable; review them with custom_tool_list and read_file")

    # -- programs ------------------------------------------------------------------

    @registry.tool(
        "write_program",
        "Write a Python program into the workspace so it can be re-run later. "
        "Use this whenever the automation is worth keeping, instead of pasting code into chat.",
        {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string",
                    "description": "File name inside the workspace, e.g. 'rename_shots.py'.",
                },
                "source": {"type": "string", "description": "The complete Python source."},
                "purpose": {
                    "type": "string",
                    "description": "One line describing what it does; becomes the file's header comment.",
                },
            },
            "required": ["path", "source"],
            "additionalProperties": False,
        },
    )
    def write_program(path: str, source: str, purpose: str = "") -> ToolResult:
        _guard_write(source, "source")
        target = workspace.resolve(path)
        if not target.endswith(".py"):
            target += ".py"
        protect_custom_tool_store(target)
        if os.path.isdir(target):
            raise ToolError("{} is a directory".format(workspace.relative(target)))
        header = PROGRAM_HEADER.format(
            purpose=(purpose or "an iOS automation").strip().splitlines()[0][:160],
            version="{}.{}".format(sys.version_info[0], sys.version_info[1]),
        )
        body = source if source.endswith("\n") else source + "\n"
        os.makedirs(os.path.dirname(target) or workspace.root, exist_ok=True)
        existed = os.path.exists(target)
        with open(target, "w", encoding="utf-8") as handle:
            handle.write(header + body)
        relative = workspace.relative(target)
        return ToolResult.ok(
            "{} {} ({} lines). Run it with run_program(\"{}\").".format(
                "Rewrote" if existed else "Wrote",
                relative,
                body.count("\n"),
                relative,
            ),
            path=relative,
            bytes=len(header) + len(body),
            overwrote=existed,
        )

    @registry.tool(
        "run_program",
        "Run a Python program and return its stdout/stderr. Pass a workspace path, or raw source to "
        "try something once. Use this to test what you wrote before telling the user it works. "
        "Keep programs short and non-blocking: on iOS they run inside this app, and a program stuck "
        "in a network call cannot be interrupted.",
        {
            "type": "object",
            "properties": {
                "path_or_source": {
                    "type": "string",
                    "description": "A workspace-relative .py path, or inline Python source.",
                },
                "args": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Command-line arguments passed to the program.",
                },
                "timeout_s": {
                    "type": "number",
                    "description": "Kill the program after this many seconds (default 30, max 300).",
                    "minimum": 0.5,
                    "maximum": MAX_RUN_TIMEOUT,
                },
            },
            "required": ["path_or_source"],
            "additionalProperties": False,
        },
        timeout=None,  # the subprocess has its own timeout; do not double-bound it
    )
    def run_program(
        path_or_source: str, args: Optional[Sequence[str]] = None, timeout_s: float = DEFAULT_RUN_TIMEOUT
    ) -> ToolResult:
        context.runs += 1
        argv = [str(a) for a in (args or [])]
        timeout = max(0.5, min(float(timeout_s or DEFAULT_RUN_TIMEOUT), MAX_RUN_TIMEOUT))
        looks_like_path = "\n" not in path_or_source and path_or_source.strip().endswith(".py")
        if looks_like_path:
            target = workspace.resolve(path_or_source.strip(), must_exist=True)
            source = None
            label = workspace.relative(target)
        else:
            target = None
            source = path_or_source
            label = "<inline source>"
        if ios.is_pyto():
            # Pyto's subprocess replacement changes process-wide cwd, streams, argv and env.
            # Share one execution lane with its embedded Unix commands to avoid cross-talk.
            with unix_tools.IN_PROCESS_EXECUTION_LOCK:
                outcome = _execute(target=target, source=source, argv=argv, cwd=workspace.root, timeout=timeout)
        else:
            outcome = _execute(target=target, source=source, argv=argv, cwd=workspace.root, timeout=timeout)
        outcome["program"] = label
        header = "{} {} in {:.2f}s ({} mode)".format(
            "TIMED OUT" if outcome["timed_out"] else ("FAILED" if outcome["returncode"] else "OK"),
            label,
            outcome["duration_s"],
            outcome["mode"],
        )
        sections = [header]
        if outcome.get("note"):
            sections.append(outcome["note"])
        if not outcome.get("timeout_enforced", True):
            # Never claim a bound that did not hold.
            sections.append("timeout enforced: false (the program removed the cooperative timeout)")
        sections.append("--- stdout ---\n{}".format(outcome["stdout"].rstrip() or "<empty>"))
        if outcome["stderr"].strip():
            sections.append("--- stderr ---\n{}".format(outcome["stderr"].rstrip()))
        sections.append("--- exit code: {} ---".format(outcome["returncode"]))
        hint = pyto_api.hint_for_stderr(outcome["stderr"], state_dir=context.state_dir or None)
        if hint:
            sections.append(hint)
        return ToolResult(
            content="\n".join(sections),
            is_error=bool(outcome["returncode"]) or outcome["timed_out"],
            metadata={
                "returncode": outcome["returncode"],
                "timed_out": outcome["timed_out"],
                "timeout_enforced": bool(outcome.get("timeout_enforced", True)),
                "mode": outcome["mode"],
                "capture_path": outcome.get("capture_path"),
                "stdout_chars": len(outcome["stdout"]),
                "stderr_chars": len(outcome["stderr"]),
                "pyto_hint": bool(hint),
            },
        )

    # -- Pyto's own libraries ------------------------------------------------------

    @registry.tool(
        "pyto_api",
        "Look up Pyto's own bundled modules and what Pyto does not have. Call this BEFORE "
        "writing a program that imports a Pyto module: with no argument it lists the modules "
        "available on this device plus everything Pyto lacks (Reminders, HealthKit, Bluetooth, "
        "speech recognition, pip install of C extensions, a daemon); with module='photos' it "
        "gives that module's real members, signatures, a minimal snippet and caveats. Pyto's "
        "API is small, version-specific and easy to misremember, so use only the members it "
        "reports. If run_program raises AttributeError/ImportError about a Pyto module, call "
        "this again for that module instead of guessing a second name.",
        {
            "type": "object",
            "properties": {
                "module": {
                    "type": "string",
                    "description": "A Pyto module, e.g. 'pasteboard', 'photos', 'pyto_ui'. Empty lists them all.",
                },
                "member": {
                    "type": "string",
                    "description": "Optional: narrow one module to a single member, e.g. 'set_string'.",
                },
            },
            "additionalProperties": False,
        },
        timeout=30.0,
    )
    def pyto_api_tool(module: str = "", member: str = "") -> ToolResult:
        text = pyto_api.render_reference(
            module or None,
            member or None,
            MAX_PYTO_REFERENCE_CHARS,
            state_dir=context.state_dir or None,
        )
        capped = "[truncated:" in text
        return ToolResult.ok(
            text,
            module=module,
            member=member,
            chars=len(text),
            capped=capped,
        )

    @registry.tool(
        "python_module_capabilities",
        "Check whether named optional Python libraries are installed in this runtime without importing them. Use this before planning around a third-party package; then test a small import on the device.",
        {
            "type": "object",
            "properties": {
                "modules": {
                    "type": "array",
                    "items": {"type": "string", "pattern": "^[A-Za-z_][A-Za-z0-9_]*$"},
                    "minItems": 1,
                    "maxItems": module_tools.MAX_MODULE_NAMES,
                    "description": "Top-level Python import names such as numpy or PIL.",
                }
            },
            "required": ["modules"],
            "additionalProperties": False,
        },
        timeout=10.0,
    )
    def python_module_capabilities(modules: Sequence[str]) -> ToolResult:
        result = module_tools.inspect_modules(modules)
        return ToolResult.ok(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True), **result)

    # -- Pyto's embedded Unix commands -------------------------------------------

    def command_inventory() -> Dict[str, Any]:
        if context.unix_inventory is None:
            context.unix_inventory = unix_tools.discover_commands(workspace.root)
        return context.unix_inventory

    @registry.tool(
        "unix_capabilities",
        "List the read-only Unix commands confirmed on this Pyto build. Call this before using unix_command; use search_files and list_files for ordinary workspace searches.",
        {"type": "object", "properties": {}, "additionalProperties": False},
        timeout=None if ios.is_pyto() else 30.0,
    )
    def unix_capabilities() -> ToolResult:
        inventory = command_inventory()
        return ToolResult.ok(
            json.dumps(inventory, ensure_ascii=False, indent=2, sort_keys=True),
            commands=inventory.get("commands", []),
            verified=bool(inventory.get("verified")),
            platform=inventory.get("platform", "unknown"),
        )

    @registry.tool(
        "unix_command",
        "Run one confirmed read-only Unix command with separate arguments and a workspace-relative file path. Call unix_capabilities first. No shell chains or file-writing options are accepted; Pyto commands share the app process and cannot be forcibly timed out.",
        {
            "type": "object",
            "properties": {
                "command": {"type": "string", "description": "A command listed by unix_capabilities."},
                "args": {
                    "type": "array",
                    "items": {"type": "string"},
                    "maxItems": unix_tools.MAX_ARGS,
                    "description": "Only the command's small documented read-only option set is accepted.",
                },
                "path": {
                    "type": "string",
                    "description": "Optional file or folder inside the workspace; never an outside Files path.",
                },
                "input_text": {
                    "type": "string",
                    "maxLength": unix_tools.MAX_INPUT_BYTES,
                    "description": "Optional text input for sort, uniq, cut, wc or grep instead of a file path.",
                },
            },
            "required": ["command"],
            "additionalProperties": False,
        },
        timeout=None if ios.is_pyto() else 35.0,
    )
    def unix_command(
        command: str,
        args: Optional[Sequence[str]] = None,
        path: str = "",
        input_text: Optional[str] = None,
    ) -> ToolResult:
        inventory = command_inventory()
        outcome = unix_tools.run_command(
            command,
            args or [],
            path=path,
            input_text=input_text,
            workspace=workspace,
            available=inventory.get("commands", []),
        )
        status = "No matches" if outcome["no_matches"] else (
            "OK" if outcome["returncode"] == 0 else "Command returned {}".format(outcome["returncode"])
        )
        sections = ["{} ({} mode)".format(status, outcome["mode"])]
        sections.append("$ {}".format(" ".join(shlex.quote(value) for value in outcome["argv"])))
        sections.append("--- stdout ---\n{}".format(outcome["stdout"].rstrip() or "<empty>"))
        if outcome["stderr"].strip():
            sections.append("--- stderr ---\n{}".format(outcome["stderr"].rstrip()))
        if not outcome["timeout_enforced"]:
            sections.append("Pyto ran this command inside the app process; no hard kill timeout is available.")
        return ToolResult(
            content="\n".join(sections),
            is_error=(outcome["returncode"] != 0 and not outcome["no_matches"]) or bool(outcome["stderr"].strip()),
            metadata={
                "command": command,
                "returncode": outcome["returncode"],
                "truncated": outcome["truncated"],
                "timeout_enforced": outcome["timeout_enforced"],
                "mode": outcome["mode"],
            },
        )

    # -- persistent custom tools --------------------------------------------------

    @registry.tool(
        "custom_tool_list",
        "List saved custom tools with their input schemas, Pyto modules and commands. Use this before calling or editing a tool you created.",
        {"type": "object", "properties": {}, "additionalProperties": False},
        timeout=15.0,
    )
    def custom_tool_list() -> ToolResult:
        result = custom_tools.list_custom_tools(workspace)
        result["load_errors"] = list(context.custom_tool_errors)
        return ToolResult.ok(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True), **result)

    @registry.tool(
        "custom_tool_create",
        "Create a persistent callable Python tool with an explicit JSON input schema. Source must define def run(inputs):. This stores code that runs with Pyto's app permissions; creation needs approval and every later invocation also needs approval.",
        {
            "type": "object",
            "properties": {
                "name": {"type": "string", "pattern": "^[a-z][a-z0-9_]{0,47}$"},
                "purpose": {"type": "string", "maxLength": custom_tools.MAX_PURPOSE_CHARS},
                "parameters": {"type": "object", "description": "A JSON Schema object describing the tool inputs."},
                "source": {
                    "type": "string",
                    "maxLength": custom_tools.MAX_SOURCE_CHARS,
                    "description": "Python source defining one synchronous def run(inputs): function.",
                },
                "required_commands": {"type": "array", "items": {"type": "string"}, "maxItems": 32},
                "required_modules": {"type": "array", "items": {"type": "string"}, "maxItems": 32},
            },
            "required": ["name", "purpose", "parameters", "source"],
            "additionalProperties": False,
        },
        timeout=30.0,
    )
    def custom_tool_create(
        name: str,
        purpose: str,
        parameters: Mapping[str, Any],
        source: str,
        required_commands: Optional[Sequence[str]] = None,
        required_modules: Optional[Sequence[str]] = None,
    ) -> ToolResult:
        if context.registry is None:
            raise ToolError("the live tool registry is unavailable")
        manifest = custom_tools.create_custom_tool(
            workspace,
            name=name,
            purpose=purpose,
            parameters=parameters,
            source=source,
            required_commands=required_commands,
            required_modules=required_modules,
        )
        custom_tools.register_custom_tool(workspace, context.registry, run_program, manifest)
        return ToolResult.ok(
            "Created custom_{} and added it to this session's tool list. Its source is {}. It will ask for approval every time it runs.".format(
                manifest["name"], manifest["source"]
            ),
            name="custom_" + manifest["name"],
            source=manifest["source"],
            source_sha256=manifest["source_sha256"],
        )

    @registry.tool(
        "custom_tool_disable",
        "Disable a saved custom tool while keeping its source and manifest so it can be reviewed or re-enabled later.",
        {
            "type": "object",
            "properties": {"name": {"type": "string", "description": "Tool name, with or without the custom_ prefix."}},
            "required": ["name"],
            "additionalProperties": False,
        },
        timeout=15.0,
    )
    def custom_tool_disable(name: str) -> ToolResult:
        if context.registry is None:
            raise ToolError("the live tool registry is unavailable")
        return ToolResult.ok(custom_tools.disable_custom_tool(workspace, name, context.registry), name=name)

    @registry.tool(
        "custom_tool_enable",
        "Re-enable a disabled custom tool only if its source still matches the reviewed manifest. It will continue to require approval each time it runs.",
        {
            "type": "object",
            "properties": {"name": {"type": "string", "description": "Tool name, with or without the custom_ prefix."}},
            "required": ["name"],
            "additionalProperties": False,
        },
        timeout=15.0,
    )
    def custom_tool_enable(name: str) -> ToolResult:
        if context.registry is None:
            raise ToolError("the live tool registry is unavailable")
        return ToolResult.ok(
            custom_tools.enable_custom_tool(workspace, name, context.registry, run_program), name=name
        )

    # -- files ---------------------------------------------------------------------

    @registry.tool(
        "list_files",
        "List files in the workspace, newest first. Use this to see what previous runs left behind.",
        {
            "type": "object",
            "properties": {
                "pattern": {"type": "string", "description": "Glob for the file name, e.g. '*.py'."},
                "subdir": {"type": "string", "description": "Limit the listing to this subdirectory."},
                "limit": {"type": "integer", "minimum": 1, "maximum": 1000, "description": "Max entries."},
            },
            "additionalProperties": False,
        },
        timeout=30.0,
    )
    def list_files(pattern: str = "*", subdir: str = "", limit: int = 200) -> ToolResult:
        root = workspace.resolve(subdir) if subdir else os.path.realpath(workspace.root)
        if not os.path.isdir(root):
            raise ToolError("{} is not a directory in the workspace".format(subdir))
        found = _iter_workspace_files(root, pattern, limit=int(limit or 200))
        if not found:
            return ToolResult.ok("No files matching {!r} in {}.".format(pattern, workspace.relative(root) or "."))
        rows = []
        for path in sorted(found, key=lambda p: -os.path.getmtime(p))[: int(limit or 200)]:
            stat = os.stat(path)
            rows.append(
                "{:>9}  {:>16}  {}".format(
                    stat.st_size, time.strftime("%Y-%m-%d %H:%M", time.localtime(stat.st_mtime)), workspace.relative(path)
                )
            )
        return ToolResult.ok(
            "{} file(s) in {}:\n{}".format(len(rows), workspace.relative(root) or ".", "\n".join(rows)),
            count=len(rows),
        )

    @registry.tool(
        "read_file",
        "Read a text file from the workspace. Use this before editing so your replacement text matches exactly.",
        {
            "type": "object",
            "properties": {
                "path": {"type": "string", "description": "Workspace-relative path."},
                "max_chars": {"type": "integer", "minimum": 1, "maximum": MAX_READ_CHARS},
            },
            "required": ["path"],
            "additionalProperties": False,
        },
        timeout=30.0,
    )
    def read_file(path: str, max_chars: int = 20000) -> ToolResult:
        target = workspace.resolve(path, must_exist=True)
        if os.path.isdir(target):
            raise ToolError("{} is a directory; use list_files".format(path))
        text, truncated = _read_text(target)
        limit = int(max_chars or 20000)
        if len(text) > limit:
            text = text[:limit] + "\n... [{} more characters; call read_file again with a larger max_chars]".format(
                len(text) - limit
            )
            truncated = True
        return ToolResult.ok(
            "{} ({} bytes{}):\n{}".format(
                workspace.relative(target),
                os.path.getsize(target),
                ", truncated" if truncated else "",
                text,
            ),
            path=workspace.relative(target),
            truncated=truncated,
        )

    @registry.tool(
        "write_file",
        "Create or overwrite a text file (notes, data, config). For Python programs prefer write_program.",
        {
            "type": "object",
            "properties": {
                "path": {"type": "string", "description": "Workspace-relative path."},
                "content": {"type": "string", "description": "Full file contents."},
            },
            "required": ["path", "content"],
            "additionalProperties": False,
        },
        timeout=30.0,
    )
    def write_file(path: str, content: str) -> ToolResult:
        _guard_write(content, "content")
        target = workspace.resolve(path)
        protect_custom_tool_store(target)
        if os.path.isdir(target):
            raise ToolError("{} is a directory".format(path))
        os.makedirs(os.path.dirname(target) or workspace.root, exist_ok=True)
        existed = os.path.exists(target)
        with open(target, "w", encoding="utf-8") as handle:
            handle.write(content)
        return ToolResult.ok(
            "{} {} ({} bytes).".format(
                "Overwrote" if existed else "Created", workspace.relative(target), len(content.encode("utf-8"))
            ),
            path=workspace.relative(target),
        )

    @registry.tool(
        "edit_file",
        "Replace an exact string in a file. Use read_file first; if the old text does not match exactly, nothing changes.",
        {
            "type": "object",
            "properties": {
                "path": {"type": "string", "description": "Workspace-relative path."},
                "old": {"type": "string", "description": "Exact text to find."},
                "new": {"type": "string", "description": "Replacement text."},
                "count": {
                    "type": "integer",
                    "minimum": 1,
                    "description": "How many occurrences to replace (default 1).",
                },
            },
            "required": ["path", "old", "new"],
            "additionalProperties": False,
        },
        timeout=30.0,
    )
    def edit_file(path: str, old: str, new: str, count: int = 1) -> ToolResult:
        target = workspace.resolve(path, must_exist=True)
        protect_custom_tool_store(target)
        if os.path.isdir(target):
            raise ToolError("{} is a directory".format(path))
        with open(target, "r", encoding="utf-8") as handle:
            text = handle.read()
        occurrences = text.count(old)
        if occurrences == 0:
            raise ToolError(
                "the exact text was not found in {}; nothing was changed. Read the file and copy the "
                "text verbatim.".format(workspace.relative(target))
            )
        replaced = text.replace(old, new, int(count or 1))
        with open(target, "w", encoding="utf-8") as handle:
            handle.write(replaced)
        return ToolResult.ok(
            "Replaced {} of {} occurrence(s) in {}.".format(
                min(int(count or 1), occurrences), occurrences, workspace.relative(target)
            ),
            path=workspace.relative(target),
            occurrences=occurrences,
        )

    # -- search --------------------------------------------------------------------

    @registry.tool(
        "search_files",
        "Search the workspace for a regex or plain string. Use this to find where something lives before reading whole files.",
        {
            "type": "object",
            "properties": {
                "query": {"type": "string", "description": "Text or regular expression to look for."},
                "pattern": {"type": "string", "description": "File-name glob, default '*'."},
                "regex": {"type": "boolean", "description": "Treat the query as a regex (default false)."},
                "ignore_case": {"type": "boolean", "description": "Case-insensitive search (default true)."},
                "limit": {
                    "type": "integer",
                    "minimum": 1,
                    "maximum": MAX_SEARCH_LIMIT,
                    "description": "Max matching lines to return.",
                },
            },
            "required": ["query"],
            "additionalProperties": False,
        },
        timeout=60.0,
    )
    def search_files(
        query: str,
        pattern: str = "*",
        regex: bool = False,
        ignore_case: bool = True,
        limit: int = DEFAULT_SEARCH_LIMIT,
    ) -> ToolResult:
        if not query:
            raise ToolError("a non-empty query is required")
        flags = re.IGNORECASE if ignore_case else 0
        try:
            matcher = re.compile(query if regex else re.escape(query), flags)
        except re.error as exc:
            raise ToolError("invalid regular expression {!r}: {}".format(query, exc)) from None
        cap = max(1, min(int(limit or DEFAULT_SEARCH_LIMIT), MAX_SEARCH_LIMIT))
        hits: List[str] = []
        files_scanned = 0
        truncated_by_cap = False
        for path in _iter_workspace_files(os.path.realpath(workspace.root), pattern, limit=2000):
            try:
                if os.path.getsize(path) > MAX_SEARCH_FILE_BYTES:
                    continue
            except OSError:
                continue
            files_scanned += 1
            try:
                with open(path, "r", encoding="utf-8", errors="replace") as handle:
                    for number, line in enumerate(handle, start=1):
                        if matcher.search(line):
                            hits.append(
                                "{}:{}: {}".format(workspace.relative(path), number, line.rstrip()[:300])
                            )
                            if len(hits) >= cap:
                                truncated_by_cap = True
                                break
            except OSError:
                continue
            if truncated_by_cap:
                break
        if not hits:
            return ToolResult.ok(
                "No match for {!r} in {} file(s) scanned.".format(query, files_scanned), matches=0
            )
        footer = "\n[stopped at the {} match cap; narrow the query or raise limit]" if truncated_by_cap else ""
        return ToolResult.ok(
            "{} match(es) across {} file(s) scanned:\n{}{}".format(len(hits), files_scanned, "\n".join(hits), footer),
            matches=len(hits),
        )

    # -- device capabilities -------------------------------------------------------

    @registry.tool(
        "clipboard_get",
        "Read whatever the user last copied. Use it when they say 'this' or 'what I copied'. "
        "Foreground only: iOS blocks clipboard access once the app is in the background.",
        {"type": "object", "properties": {}, "additionalProperties": False},
        timeout=15.0,
    )
    def clipboard_get() -> ToolResult:
        result = ios.clipboard_get()
        if not result.supported:
            raise ToolError(result.detail)
        if not result.ok:
            raise ToolError(result.detail)
        text = result.data.get("text", "")
        if not text:
            return ToolResult.ok("The clipboard is empty.")
        return ToolResult.ok("Clipboard ({} characters):\n{}".format(len(text), text), chars=len(text))

    @registry.tool(
        "clipboard_set",
        "Copy text to the clipboard so the user can paste it elsewhere. "
        "Foreground only: the clipboard cannot be written while the app is backgrounded.",
        {
            "type": "object",
            "properties": {"text": {"type": "string", "description": "Text to copy."}},
            "required": ["text"],
            "additionalProperties": False,
        },
        timeout=15.0,
        danger="writes to the shared system clipboard",
    )
    def clipboard_set(text: str) -> ToolResult:
        result = ios.clipboard_set(text)
        if not result.ok:
            raise ToolError(result.detail)
        return ToolResult.ok("Copied {} characters to the clipboard.".format(len(text)))

    @registry.tool(
        "share_text",
        "Open the iOS share sheet with text (Messages, Mail, Notes...). Ask the user before sharing anything.",
        {
            "type": "object",
            "properties": {
                "text": {"type": "string", "description": "The text to share."},
                "title": {"type": "string", "description": "Optional short label."},
            },
            "required": ["text"],
            "additionalProperties": False,
        },
        timeout=30.0,
        danger="shares text outside the app",
    )
    def share_text(text: str, title: str = "") -> ToolResult:
        result = ios.share_text(text, title=title)
        if not result.ok:
            raise ToolError(result.detail)
        return ToolResult.ok(result.render())

    @registry.tool(
        "open_url",
        "Open a URL or an app's URL scheme in Safari or the matching app.",
        {
            "type": "object",
            "properties": {"url": {"type": "string", "description": "Absolute URL, including the scheme."}},
            "required": ["url"],
            "additionalProperties": False,
        },
        timeout=30.0,
        danger="leaves the app and opens an external URL",
    )
    def open_url(url: str) -> ToolResult:
        if "://" not in url:
            raise ToolError("the url needs a scheme, e.g. https://example.com")
        result = ios.open_url(url)
        if not result.ok:
            raise ToolError(result.detail)
        return ToolResult.ok(result.render())

    @registry.tool(
        "notify",
        "Post a local notification, e.g. to tell the user a long job finished. Needs notification permission.",
        {
            "type": "object",
            "properties": {
                "title": {"type": "string", "description": "Bold first line."},
                "body": {"type": "string", "description": "Optional second line."},
            },
            "required": ["title"],
            "additionalProperties": False,
        },
        timeout=15.0,
    )
    def notify(title: str, body: str = "") -> ToolResult:
        result = ios.notify(title, body)
        if not result.supported:
            raise ToolError(result.detail)
        if not result.ok:
            raise ToolError(result.detail)
        return ToolResult.ok(result.render())

    @registry.tool(
        "speak",
        "Read text aloud through the speaker. Use it when the user asks for audio rather than text.",
        {
            "type": "object",
            "properties": {"text": {"type": "string", "description": "Text to speak."}},
            "required": ["text"],
            "additionalProperties": False,
        },
        timeout=30.0,
        danger="plays audio out loud",
    )
    def speak(text: str) -> ToolResult:
        result = ios.speak(text)
        if not result.supported:
            raise ToolError(result.detail)
        if not result.ok:
            raise ToolError(result.detail)
        return ToolResult.ok(result.render())

    @registry.tool(
        "shortcut_run",
        "Run one of the user's iOS Shortcuts by name, optionally passing input text. "
        "Confirm the exact Shortcut name with the user first.",
        {
            "type": "object",
            "properties": {
                "name": {"type": "string", "description": "Exact Shortcut name as shown in the Shortcuts app."},
                "input_text": {"type": "string", "description": "Optional text handed to the Shortcut."},
            },
            "required": ["name"],
            "additionalProperties": False,
        },
        timeout=30.0,
        danger="runs an automation outside the app that may change data or spend money",
    )
    def shortcut_run(name: str, input_text: str = "") -> ToolResult:
        result = ios.shortcut_run(name, input_text)
        if not result.ok:
            raise ToolError(result.detail)
        return ToolResult.ok(result.render(), url=result.data.get("url"))

    @registry.tool(
        "save_photo",
        "Save an image file from the workspace into the user's photo library. Needs photo permission.",
        {
            "type": "object",
            "properties": {"path": {"type": "string", "description": "Workspace-relative image path."}},
            "required": ["path"],
            "additionalProperties": False,
        },
        timeout=30.0,
        danger="writes to the user's photo library",
    )
    def save_photo(path: str) -> ToolResult:
        target = workspace.resolve(path, must_exist=True)
        result = ios.save_photo(target)
        if not result.supported:
            raise ToolError(result.detail)
        if not result.ok:
            raise ToolError(result.detail)
        return ToolResult.ok(result.render())

    @registry.tool(
        "open_in_files",
        "Reveal a workspace path in the Files app so the user can see or move it themselves.",
        {
            "type": "object",
            "properties": {"path": {"type": "string", "description": "Optional workspace-relative path."}},
            "additionalProperties": False,
        },
        timeout=30.0,
        danger="switches to the Files app",
    )
    def open_in_files(path: str = "") -> ToolResult:
        target = workspace.resolve(path) if path else workspace.root
        result = ios.open_in_files(target)
        if not result.ok:
            raise ToolError(result.detail)
        return ToolResult.ok(result.render())

    @registry.tool(
        "shortcut_run_wait",
        "Run a Shortcut and ask iOS to hand its output back via x-callback-url. Use this instead of "
        "shortcut_run when you need the Shortcut's result; the reply arrives as a `result` URL parameter.",
        {
            "type": "object",
            "properties": {
                "name": {"type": "string", "description": "Exact Shortcut name."},
                "input_text": {"type": "string", "description": "Optional text handed to the Shortcut."},
                "callback": {"type": "string", "description": "Callback URL, default 'pyto://'."},
            },
            "required": ["name"],
            "additionalProperties": False,
        },
        timeout=30.0,
        danger="runs an automation outside the app that may change data or spend money",
    )
    def shortcut_run_wait(name: str, input_text: str = "", callback: str = "pyto://") -> ToolResult:
        result = ios.shortcut_run_wait(name, input_text, callback=callback)
        if not result.ok:
            raise ToolError(result.detail)
        return ToolResult.ok(
            "{}\nThe Shortcut's output comes back as the `result` parameter of {}".format(
                result.render(), callback
            ),
            url=result.data.get("url"),
        )

    @registry.tool(
        "calendar_add_event",
        "Add an event to the user's calendar. Use ISO local times like 2024-05-01T09:00. "
        "Confirm the details with the user before writing to their calendar.",
        {
            "type": "object",
            "properties": {
                "title": {"type": "string", "description": "Event title."},
                "start_iso": {"type": "string", "description": "Start time, e.g. 2024-05-01T09:00."},
                "end_iso": {"type": "string", "description": "End time; defaults to one hour after the start."},
                "notes": {"type": "string", "description": "Optional notes."},
                "calendar": {"type": "string", "description": "Optional calendar name."},
            },
            "required": ["title", "start_iso"],
            "additionalProperties": False,
        },
        timeout=30.0,
        danger="writes to the user's calendar",
    )
    def calendar_add_event(
        title: str, start_iso: str, end_iso: str = "", notes: str = "", calendar: str = ""
    ) -> ToolResult:
        result = ios.calendar_add_event(title, start_iso, end_iso, notes=notes, calendar=calendar)
        if not result.supported:
            raise ToolError(result.detail)
        if not result.ok:
            raise ToolError(result.detail)
        return ToolResult.ok(result.render())

    @registry.tool(
        "calendar_list_events",
        "List the user's upcoming calendar events. Use it before proposing times or planning a day.",
        {
            "type": "object",
            "properties": {
                "days": {"type": "integer", "minimum": 1, "maximum": 365, "description": "How far ahead to look."}
            },
            "additionalProperties": False,
        },
        timeout=30.0,
    )
    def calendar_list_events(days: int = 7) -> ToolResult:
        result = ios.calendar_list_events(int(days or 7))
        if not result.supported:
            raise ToolError(result.detail)
        if not result.ok:
            raise ToolError(result.detail)
        lines = []
        for event in result.data.get("events") or []:
            if "repr" in event:
                lines.append(event["repr"])
            else:
                lines.append("{}  {} -> {}".format(event.get("title"), event.get("start"), event.get("end")))
        return ToolResult.ok(
            "{}\n{}".format(result.render(), "\n".join(lines) if lines else "<no events>"),
            count=len(lines),
        )

    @registry.tool(
        "keepalive_start",
        "Ask iOS to keep this script running for a while after the user leaves the app. Only useful for "
        "a long job the user explicitly wants finished; stop it as soon as the work is done.",
        {
            "type": "object",
            "properties": {"label": {"type": "string", "description": "Short label for the task."}},
            "additionalProperties": False,
        },
        timeout=15.0,
        danger="keeps the app running in the background (a store-review grey area)",
    )
    def keepalive_start(label: str = "pyto-harness") -> ToolResult:
        result = ios.keepalive_start(label)
        if not result.ok:
            raise ToolError(result.detail)
        return ToolResult.ok(result.render())

    @registry.tool(
        "keepalive_stop",
        "Stop the background task started by keepalive_start.",
        {"type": "object", "properties": {}, "additionalProperties": False},
        timeout=15.0,
    )
    def keepalive_stop() -> ToolResult:
        result = ios.keepalive_stop()
        if not result.ok:
            raise ToolError(result.detail)
        return ToolResult.ok(result.render())

    @registry.tool(
        "memory_status",
        "Report free memory. Check it before writing big files: Pyto stops every running script when "
        "free memory gets near 500 MB.",
        {"type": "object", "properties": {}, "additionalProperties": False},
        timeout=15.0,
    )
    def memory_status() -> ToolResult:
        result = ios.memory_status()
        detail = result.render()
        if result.supported and (result.data.get("available_mb") or 0) < 600:
            detail += "\nMemory is critically low: write small files and avoid loading anything large."
        return ToolResult.ok(detail, **{k: v for k, v in result.data.items()})

    @registry.tool(
        "device_capabilities",
        "Report which iOS features are available right now (clipboard, share, speech, photos...). "
        "Call this when a device action fails unexpectedly.",
        {"type": "object", "properties": {}, "additionalProperties": False},
        timeout=15.0,
    )
    def device_capabilities() -> ToolResult:
        return ToolResult.ok(ios.capability_report(), **ios.available_capabilities())

    # -- memory --------------------------------------------------------------------

    @registry.tool(
        "memory_read",
        "Read the saved facts and preferences about this user (name, folders, routines). "
        "Check it at the start of a task so you do not re-ask things they already told you.",
        {"type": "object", "properties": {}, "additionalProperties": False},
        timeout=15.0,
    )
    def memory_read() -> ToolResult:
        facts = _load_memory(context)
        if not facts:
            return ToolResult.ok("No saved facts yet. Use memory_write to remember something about the user.")
        lines = ["{}: {}".format(key, _render_fact(value)) for key, value in sorted(facts.items())]
        return ToolResult.ok("{} saved fact(s):\n{}".format(len(facts), "\n".join(lines)), count=len(facts))

    @registry.tool(
        "memory_write",
        "Save a durable fact or preference about the user, e.g. ('screenshots_folder', '~/Screenshots'). "
        "Use it whenever they state a preference you would otherwise ask about again.",
        {
            "type": "object",
            "properties": {
                "key": {"type": "string", "description": "Short snake_case key.", "pattern": "^[A-Za-z0-9_.-]{1,64}$"},
                "value": {"type": "string", "description": "The fact. Keep it short and literal."},
            },
            "required": ["key", "value"],
            "additionalProperties": False,
        },
        timeout=15.0,
    )
    def memory_write(key: str, value: str) -> ToolResult:
        facts = _load_memory(context)
        replaced = key in facts
        facts[key] = value
        _save_memory(context, facts)
        return ToolResult.ok(
            "{} memory[{!r}] = {!r}. {} fact(s) stored.".format(
                "Updated" if replaced else "Saved", key, value, len(facts)
            ),
            key=key,
            replaced=replaced,
        )

    # -- self-diagnosis and self-repair ---------------------------------------------

    def doctor_context(*, network: bool = False, deep: bool = False) -> Any:
        """Build a doctor context from this tool context."""
        resolved = context.config
        if resolved is None:
            try:
                resolved = load_config(use_env=True)
            except ConfigError:
                resolved = Config()
        if not resolved.workspace:
            resolved.workspace = context.workspace.root
        return doctor.DoctorContext.for_config(
            resolved,
            config_path=context.config_path or None,
            root=context.harness_root or None,
            state=context.state_dir or None,
            workspace=context.workspace.root,
            network=network,
            deep=deep,
            persist=True,
        )

    @registry.tool(
        "diagnose",
        "Run the harness's own health checks: interpreter, imports, config, key shape, workspace, "
        "session logs, memory, iOS modules. Use it when something fails twice for the same reason, "
        "before you start guessing. It is local and free unless you pass network=true, which adds "
        "DNS/TLS/auth checks and costs one tiny API request.",
        {
            "type": "object",
            "properties": {
                "network": {
                    "type": "boolean",
                    "description": "Also check DNS/TLS and test the key with one minimal request.",
                },
                "deep": {"type": "boolean", "description": "Also run the harness's offline test suite."},
            },
            "additionalProperties": False,
        },
        timeout=300.0,
    )
    def diagnose(network: bool = False, deep: bool = False) -> ToolResult:
        ctx = doctor_context(network=network, deep=deep)
        results = doctor.run_checks(ctx, network=network)
        doctor.save_health(ctx, results)
        text = doctor.compact_report(results, limit=1500)
        failing = [item.id for item in results if item.failed()]
        return ToolResult.ok(
            text,
            unhealthy=len(failing),
            ids=failing,
            exit_code=doctor.exit_code(results),
            fixable=[item.fix_id for item in results if item.fix_id],
        )

    @registry.tool(
        "apply_fix",
        "Apply one named fix that diagnose reported (e.g. 'workspace.create', 'api_base.rewrite'). "
        "Runs exactly that fix and re-checks the affected part. Every fix is additive: directories, "
        "file modes, a torn log line, the api_base or model name, SHORTCUTS.md. Nothing is deleted, "
        "and the API key is never written or read back.",
        {
            "type": "object",
            "properties": {
                "fix_id": {"type": "string", "description": "A fix id from diagnose, e.g. 'config.chmod'."}
            },
            "required": ["fix_id"],
            "additionalProperties": False,
        },
        timeout=1200.0,
    )
    def apply_fix(fix_id: str) -> ToolResult:
        ctx = doctor_context(network=True)
        if fix_id not in doctor.FIXES:
            raise ToolError(
                "unknown fix {!r}; known fixes: {}".format(fix_id, ", ".join(sorted(doctor.FIXES)))
            )
        outcome = doctor.apply_fix(ctx, fix_id)
        check_id = doctor.FIXES[fix_id].check_id
        fresh = doctor.run_one(ctx, check_id)
        doctor.save_health(ctx, doctor.run_checks(ctx, network=False))
        text = "{}\ncheck {} is now: {} ({})".format(outcome.render(), check_id, fresh.status, fresh.detail)
        if fresh.human_action:
            text += "\nonly the user can do this next: {}".format(fresh.human_action)
        return ToolResult(
            content=text,
            is_error=not outcome.ok,
            metadata={"fix_id": fix_id, "applied": outcome.ok, "status": fresh.status},
        )

    @registry.tool(
        "selftest",
        "Run this harness's own offline test suite and report the counts. This is the gate that "
        "decides whether a self_edit is kept, so run it before you propose one. Fast subset by "
        "default; pass full=true for everything (slower).",
        {
            "type": "object",
            "properties": {
                "full": {"type": "boolean", "description": "Run every test module, not the fast subset."}
            },
            "additionalProperties": False,
        },
        timeout=1200.0,
    )
    def selftest(full: bool = False) -> ToolResult:
        ctx = doctor_context()
        report = doctor.run_offline_tests(ctx, modules=None if full else doctor.FAST_TEST_MODULES)
        head = "offline tests: {ran} ran, {failures} failure(s), {errors} error(s), {skipped} skipped ({mode})".format(
            ran=report.get("ran"),
            failures=report.get("failures"),
            errors=report.get("errors"),
            skipped=report.get("skipped"),
            mode=report.get("mode"),
        )
        text = head
        if not report.get("ok"):
            tail = (report.get("output_tail") or report.get("error") or "")[-2000:]
            text += "\n" + tail
        return ToolResult(
            content=text,
            is_error=not bool(report.get("ok")),
            metadata={
                "ok": bool(report.get("ok")),
                "ran": report.get("ran"),
                "failures": report.get("failures"),
                "errors": report.get("errors"),
                "mode": report.get("mode"),
            },
        )

    @registry.tool(
        "read_source",
        "Read one of this harness's own source files (harness/*.py or run.py) before editing it. "
        "The workspace file tools cannot reach these paths; this is the only way to see the code "
        "you are about to change with self_edit.",
        {
            "type": "object",
            "properties": {
                "path": {"type": "string", "description": "e.g. 'harness/config.py'."},
                "max_chars": {"type": "integer", "minimum": 100, "description": "Read cap (default 200000)."},
            },
            "required": ["path"],
            "additionalProperties": False,
        },
        timeout=60.0,
    )
    def read_source_tool(path: str, max_chars: int = 200000) -> ToolResult:
        outcome = repair.read_source(path, root=context.harness_root or None, max_chars=int(max_chars or 200000))
        if not outcome.ok:
            raise ToolError(outcome.reason)
        return ToolResult.ok(
            "{} ({} bytes)\n{}".format(outcome.path, len(outcome.text.encode("utf-8")), outcome.text),
            path=outcome.path,
        )

    @registry.tool(
        "self_edit",
        "Change this harness's own source. Prefer the smallest change: pass old_string/new_string for "
        "a surgical patch, or new_source for a whole (small) file. The change is written, then a "
        "bounded slice of the offline test suite runs (the modules that cover the file, a few "
        "seconds): kept only if it passes, otherwise the previous bytes are restored and you are told "
        "exactly why. Read the file with read_source first, and run selftest before editing. Pass "
        "full_tests=true only when the change is broad enough to need the whole suite. Do not use "
        "this to work around a missing iOS permission: report the user action instead.",
        {
            "type": "object",
            "properties": {
                "path": {"type": "string", "description": "Relative path: harness/... or run.py."},
                "new_source": {"type": "string", "description": "The complete new file (omit when patching)."},
                "old_string": {"type": "string", "description": "Exact text to replace (patch mode)."},
                "new_string": {"type": "string", "description": "Replacement text (patch mode)."},
                "reason": {"type": "string", "description": "One line: what problem this fixes."},
                "full_tests": {
                    "type": "boolean",
                    "description": "Gate on the whole suite instead of the covering subset (slower).",
                },
            },
            "required": ["path", "reason"],
            "additionalProperties": False,
        },
        timeout=1800.0,
    )
    def self_edit(
        path: str,
        reason: str,
        new_source: str = "",
        old_string: str = "",
        new_string: str = "",
        full_tests: bool = False,
    ) -> ToolResult:
        if old_string:
            outcome = repair.apply_source_patch(
                path,
                old_string,
                new_string,
                reason,
                root=context.harness_root or None,
                backups_dir=os.path.join(context.state_dir, "backups") if context.state_dir else None,
                full_gate=bool(full_tests or context.full_gate),
            )
        elif new_source:
            outcome = repair.apply_source_edit(
                path,
                new_source,
                reason,
                root=context.harness_root or None,
                backups_dir=os.path.join(context.state_dir, "backups") if context.state_dir else None,
                full_gate=bool(full_tests or context.full_gate),
            )
        else:
            raise ToolError("provide either new_source, or old_string with new_string")
        text = outcome.render()
        if len(text) > 6000:
            text = text[:6000] + "\n... (truncated)"
        return ToolResult(
            content=text,
            is_error=not outcome.ok,
            metadata={
                "ok": outcome.ok,
                "decision": outcome.decision,
                "path": outcome.path,
                "backup_id": outcome.backup_id,
                "tests": outcome.tests,
            },
        )

    @registry.tool(
        "list_backups",
        "List the source snapshots this harness has taken (before edits, before restores). "
        "Use it to find a backup_id for restore_backup.",
        {"type": "object", "properties": {}, "additionalProperties": False},
        timeout=60.0,
    )
    def list_backups_tool() -> ToolResult:
        backups = repair.list_backups(
            backups_dir=os.path.join(context.state_dir, "backups") if context.state_dir else None
        )
        if not backups:
            return ToolResult.ok("No backups yet.", count=0)
        lines = []
        for entry in backups[:20]:
            when = time.strftime("%Y-%m-%d %H:%M", time.localtime((entry.get("created_at") or 0) / 1000))
            lines.append(
                "{}  {}  {} file(s), {} bytes{}".format(
                    entry["id"], when, entry.get("files", 0), entry.get("bytes", 0),
                    "  [{}]".format(entry["error"]) if entry.get("error") else "",
                )
            )
        return ToolResult.ok("{} backup(s):\n{}".format(len(backups), "\n".join(lines)), count=len(backups))

    @registry.tool(
        "restore_backup",
        "Put a source snapshot back, then run the offline test suite. The current tree is snapshotted "
        "first, so a restore is itself undoable. If the tests fail afterwards you will be told loudly.",
        {
            "type": "object",
            "properties": {"backup_id": {"type": "string", "description": "An id from list_backups."}},
            "required": ["backup_id"],
            "additionalProperties": False,
        },
        timeout=1800.0,
    )
    def restore_backup(backup_id: str) -> ToolResult:
        outcome = repair.restore(
            backup_id,
            root=context.harness_root or None,
            backups_dir=os.path.join(context.state_dir, "backups") if context.state_dir else None,
            full_gate=bool(context.full_gate),
        )
        text = outcome.render(with_diff=False)
        return ToolResult(
            content=text,
            is_error=not outcome.ok,
            metadata={
                "ok": outcome.ok,
                "decision": outcome.decision,
                "backup_id": outcome.backup_id,
                "tests": outcome.tests,
            },
        )

    # -- finish --------------------------------------------------------------------

    @registry.tool(
        "finish",
        "End the turn with your answer to the user. Call this when the task is done or you need their input. "
        "Write the summary for a non-programmer: what you did, what to run, what it produced.",
        {
            "type": "object",
            "properties": {
                "message": {"type": "string", "description": "The user-facing summary, plain language."}
            },
            "required": ["message"],
            "additionalProperties": False,
        },
        inline=True,
        timeout=5.0,
    )
    def finish(message: str) -> ToolResult:
        context.finished = True
        context.finish_message = message
        # `finished` in the metadata is the only channel the loop reads, so a turn ends
        # because the model said so and not because a module-level flag was set.
        return ToolResult.ok(
            "Turn finished. Summary delivered to the user.", finished=True, message=message
        )

    context.custom_tool_errors = custom_tools.register_custom_tools(workspace, registry, run_program)
    return registry


# --------------------------------------------------------------------------------------
# Memory store
# --------------------------------------------------------------------------------------


def memory_file(context: ToolContext) -> str:
    return context.memory_path or os.path.join(context.workspace.root, "memory.json")


def _load_memory(context: ToolContext) -> Dict[str, Any]:
    path = memory_file(context)
    if not os.path.exists(path):
        return {}
    try:
        with open(path, "r", encoding="utf-8") as handle:
            payload = json.load(handle)
    except (OSError, ValueError):
        # A corrupt memory file must not break the turn; keep the bad copy for the user.
        try:
            with open(path, "rb") as handle:
                write_private(path + ".corrupt", handle.read())
        except OSError:  # pragma: no cover - filesystem dependent
            pass
        return {}
    if not isinstance(payload, dict):
        return {}
    facts = payload.get("facts")
    if isinstance(facts, dict):
        return {str(k): v for k, v in facts.items()}
    return {}


def _guard_write(content: str, field: str) -> None:
    """Refuse a single write big enough to threaten the process on a memory-tight device."""
    size = len(content.encode("utf-8"))
    reason = budget.check_write_size(size)
    if reason:
        raise ToolError(
            "{}: {}. Write it in pieces with edit_file, or keep the data in a program that "
            "reads it from somewhere else.".format(field, reason)
        )

def _save_memory(context: ToolContext, facts: Mapping[str, Any]) -> None:
    path = memory_file(context)
    payload = {
        "version": 1,
        "updated_at": int(time.time()),
        "facts": {str(k): v for k, v in facts.items()},
    }
    mkdir_private(os.path.dirname(path) or ".")
    temporary = path + ".tmp"
    with open_private(temporary, truncate=True) as handle:
        json.dump(payload, handle, indent=2, ensure_ascii=False, sort_keys=True)
        handle.write("\n")
    os.replace(temporary, path)  # atomic: an iOS kill cannot leave half a memory file
    if os.name == "posix":
        # os.replace keeps the mode of the temporary; make the final name owner-only too.
        security_chmod(path)


def _render_fact(value: Any) -> str:
    if isinstance(value, str):
        return value
    return json.dumps(value, ensure_ascii=False)


# --------------------------------------------------------------------------------------
# Program execution
# --------------------------------------------------------------------------------------


def _execute(
    *,
    target: Optional[str],
    source: Optional[str],
    argv: Sequence[str],
    cwd: str,
    timeout: float,
) -> Dict[str, Any]:
    """Run a program, choosing the mechanism the platform can actually honour.

    On a desktop the subprocess path is used because it is genuinely killable: the child
    gets its own session and a timeout terminates the whole process group.

    **On Pyto it is not.** ``subprocess.Popen`` there is an in-process shim: ``kill()``
    and ``terminate()`` are no-ops and ``os.fork`` is a stub, so a "timeout kill" would
    silently never kill anything while telling the user it had.  On device the program
    therefore runs in-process via ``runpy`` with redirected stdio and a *cooperative*
    timeout that raises inside the running code.
    """
    started = time.monotonic()
    if ios.has_fake_subprocess():
        return _run_in_process(
            target=target, source=source, argv=argv, cwd=cwd, timeout=timeout, started=started
        )
    executable = sys.executable
    if target is not None and executable and os.path.exists(executable):
        try:
            return _run_subprocess_file(executable, target, argv, cwd, timeout, started)
        except OSError:
            pass  # e.g. the app bundle refuses to spawn; fall back to runpy
    return _run_in_process(
        target=target, source=source, argv=argv, cwd=cwd, timeout=timeout, started=started
    )


def _run_subprocess_file(
    executable: str,
    target: str,
    argv: Sequence[str],
    cwd: str,
    timeout: float,
    started: float,
) -> Dict[str, Any]:
    command = [executable, target] + list(argv)
    popen_kwargs: Dict[str, Any] = {
        "stdout": subprocess.PIPE,
        "stderr": subprocess.PIPE,
        "stdin": subprocess.DEVNULL,
        "cwd": cwd,
        # The child is a program the model wrote: it gets no API key and no
        # PYTO_HARNESS_* configuration.  A real process boundary is the only place the
        # harness can enforce that, which is exactly why it is enforced here.
        "env": scrubbed_environ(),
    }
    if hasattr(os, "setsid"):
        # Its own session/process group, so a timeout can kill the whole tree rather
        # than leaving an orphan holding the pipe open.
        popen_kwargs["start_new_session"] = True
    process = subprocess.Popen(command, **popen_kwargs)  # type: ignore[arg-type]
    streams: Dict[str, Dict[str, Any]] = {}
    readers = []
    for name, pipe in (("stdout", process.stdout), ("stderr", process.stderr)):
        store: Dict[str, Any] = {"data": bytearray()}
        streams[name] = store
        readers.append(
            threading.Thread(
                target=_drain, args=(pipe, store, RUN_CAPTURE_BYTES), name="pyto-{}".format(name), daemon=True
            )
        )
    for reader in readers:
        reader.start()

    timed_out = False
    try:
        returncode = process.wait(timeout=timeout)
    except subprocess.TimeoutExpired:
        timed_out = True
        returncode = _terminate_group(process)
        try:
            process.wait(timeout=5)
        except subprocess.TimeoutExpired:  # pragma: no cover - SIGKILL should be enough
            process.kill()
    for reader in readers:
        reader.join(timeout=5)

    note = ""
    if timed_out:
        note = "The program was still running after {}s and was killed (process group terminated).".format(timeout)
    capture_path = None
    truncated = any(store.get("truncated") for store in streams.values())
    if sum(len(store["data"]) for store in streams.values()) > RUN_CAPTURE_CHARS or truncated:
        capture_path = _spill_capture(cwd, target, streams)
        note = (note + " " if note else "") + "Full output saved to {}".format(capture_path)
    return {
        "mode": "subprocess",
        "stdout": _decode(streams["stdout"]),
        "stderr": _decode(streams["stderr"]),
        "returncode": returncode,
        "timed_out": timed_out,
        "timeout_enforced": True,  # a real process group was killed at the deadline
        "duration_s": time.monotonic() - started,
        "note": note,
        "capture_path": capture_path,
    }


def _drain(pipe: Any, store: Dict[str, Any], limit: int) -> None:
    """Read a pipe to exhaustion, keeping at most ``limit`` bytes."""
    if pipe is None:  # pragma: no cover - PIPE always yields a file object
        return
    try:
        while True:
            chunk = pipe.read(65536)
            if not chunk:
                break
            if len(store["data"]) < limit:
                store["data"].extend(chunk[: limit - len(store["data"])])
            else:
                store["truncated"] = True
    except (OSError, ValueError):  # pragma: no cover - pipe closed under us
        pass
    finally:
        try:
            pipe.close()
        except Exception:  # noqa: BLE001
            pass


def _terminate_group(process: "subprocess.Popen[bytes]") -> int:
    """SIGTERM the process group, then SIGKILL it.  Returns the best-known exit code."""
    killed_group = False
    if hasattr(os, "killpg") and hasattr(os, "getpgid"):
        try:
            os.killpg(os.getpgid(process.pid), signal.SIGTERM)
            killed_group = True
        except (ProcessLookupError, PermissionError, OSError):
            killed_group = False
    if not killed_group:
        try:
            process.terminate()
        except OSError:  # pragma: no cover
            pass
    try:
        return process.wait(timeout=3)
    except subprocess.TimeoutExpired:
        pass
    if killed_group:
        try:
            os.killpg(os.getpgid(process.pid), signal.SIGKILL)
        except (ProcessLookupError, PermissionError, OSError):  # pragma: no cover
            pass
    try:
        process.kill()
    except OSError:  # pragma: no cover
        pass
    try:
        return process.wait(timeout=3)
    except subprocess.TimeoutExpired:  # pragma: no cover
        return -9


def _decode(store: Mapping[str, Any]) -> str:
    text = bytes(store["data"]).decode("utf-8", "replace")
    if store.get("truncated"):
        text += "\n... [output exceeded {} KiB and was cut off]".format(RUN_CAPTURE_BYTES // 1024)
    if len(text) > RUN_CAPTURE_CHARS:
        text = text[:RUN_CAPTURE_CHARS] + "\n... [{} more characters]".format(len(text) - RUN_CAPTURE_CHARS)
    return text


def _spill_capture(cwd: str, target: Optional[str], streams: Mapping[str, Mapping[str, Any]]) -> Optional[str]:
    name = os.path.basename(target) if target else "inline"
    directory = os.path.join(cwd, "tool-output")
    try:
        mkdir_private(directory)
        path = os.path.join(directory, "run-{}-{}.log".format(name.replace(".py", ""), int(time.time() * 1000)))
        body = "### stdout\n{}\n### stderr\n{}".format(
            _decode(streams["stdout"]), _decode(streams["stderr"])
        )
        write_private(path, scrub_secrets(body))
        return path
    except OSError:  # pragma: no cover - filesystem dependent
        return None


class _BoundedTextSink(io.TextIOBase):
    """A write-through stdout/stderr sink that keeps at most ``limit`` characters.

    The previous shape was an unbounded :class:`io.StringIO` truncated *after* the program
    finished, so a program printing 64 MiB grew the process by 64 MiB before the
    20 000-character cap applied — on a phone with a ~500 MB watchdog that is exactly the
    crash the cap is documented to prevent.  This sink counts what it drops instead of
    keeping it, so peak memory is O(cap) rather than O(output).
    """

    def __init__(self, limit: int) -> None:
        super().__init__()
        self._limit = max(0, int(limit))
        self._chunks: List[str] = []
        self._kept = 0
        self._dropped = 0

    # -- io.TextIOBase surface a program (or `print`) may touch ---------------------

    def writable(self) -> bool:
        return True

    def isatty(self) -> bool:
        return False

    def flush(self) -> None:  # nothing is buffered outside the process
        return None

    @property  # type: ignore[override]
    def encoding(self) -> str:
        return "utf-8"

    def write(self, text: Any) -> int:
        if not isinstance(text, str):
            text = str(text)
        room = self._limit - self._kept
        if room > 0:
            kept = text[:room]
            self._chunks.append(kept)
            self._kept += len(kept)
        if len(text) > room:
            self._dropped += len(text) - max(room, 0)
        return len(text)

    def value(self) -> str:
        """The kept prefix plus the same marker ``_cap`` used to append."""
        text = "".join(self._chunks)
        if self._dropped:
            text += "\n... [{} more characters]".format(self._dropped)
        return text

    @property
    def dropped_chars(self) -> int:
        return self._dropped


def _run_in_process(
    *,
    target: Optional[str],
    source: Optional[str],
    argv: Sequence[str],
    cwd: str,
    timeout: float,
    started: float,
) -> Dict[str, Any]:
    """In-process execution with redirected stdio and a cooperative timeout.

    The timeout is enforced by a trace function that raises between bytecode boundaries.
    That means it **does** interrupt a pure-Python loop (the common case for a runaway
    script) and it **cannot** interrupt a program blocked inside a C call — DNS, a socket
    read, a large decode.  It is also opt-out: ``sys.settrace(None)`` from inside the
    program removes it, and no in-process mechanism can prevent that.  When it happens the
    result says ``timeout enforced: false`` instead of claiming the program was bounded.

    The program does not see the harness's credentials: ``os.environ`` is scrubbed for the
    duration of the run (and restored afterwards, whatever happens).
    """
    stdout_sink = _BoundedTextSink(RUN_CAPTURE_CHARS)
    stderr_sink = _BoundedTextSink(RUN_CAPTURE_CHARS)
    outcome: Dict[str, Any] = {}
    deadline = time.monotonic() + timeout

    def timeout_tracer(frame: Any, event: str, arg: Any) -> Any:
        if time.monotonic() > deadline:
            raise _ProgramTimeout("timed out after {:.1f}s".format(timeout))
        return timeout_tracer

    def body() -> None:
        """Run the program; every failure mode becomes an ``outcome`` entry."""
        try:
            os.chdir(cwd)
        except OSError as exc:
            # A deleted or unreadable workspace used to escape as a FileNotFoundError
            # traceback from outside the try: it is a clean, actionable tool error now.
            outcome["returncode"] = 1
            outcome["error"] = "the workspace {} is not usable: {}: {}".format(cwd, type(exc).__name__, exc)
            outcome["workspace_error"] = True
            stderr_sink.write(
                "[pyto-harness] {}\nRe-create the workspace (run.py does it automatically) and try again.\n".format(
                    outcome["error"]
                )
            )
            return
        sys.settrace(timeout_tracer)
        try:
            if target is not None:
                runpy.run_path(target, run_name="__main__")
            else:
                exec(
                    compile(source or "", "<inline>", "exec"),
                    {"__name__": "__main__", "__file__": "<inline>"},
                )
            outcome["returncode"] = 0
        except _ProgramTimeout as exc:
            outcome["returncode"] = 124
            outcome["timed_out"] = True
            outcome["error"] = str(exc)
            stdout_sink.write("\n[pyto-harness] program stopped: {}\n".format(exc))
        except SystemExit as exc:
            code = exc.code
            outcome["returncode"] = 0 if code is None else (code if isinstance(code, int) else 1)
        except BaseException as exc:  # noqa: BLE001 - report it the way a traceback would
            import traceback

            traceback.print_exc(file=stderr_sink)
            outcome["returncode"] = 1
            outcome["error"] = "{}: {}".format(type(exc).__name__, exc)
        finally:
            # If the program cleared or replaced the tracer, the deadline did not apply to
            # it and the result must not imply that it did.
            outcome["tracer_intact"] = sys.gettrace() is timeout_tracer

    def run() -> None:
        saved_stdout, saved_stderr, saved_argv = sys.stdout, sys.stderr, sys.argv
        saved_trace = sys.gettrace()
        sys.stdout, sys.stderr = stdout_sink, stderr_sink
        sys.argv = ([] if target is None else [target]) + list(argv)
        original_cwd: Optional[str] = None
        try:
            original_cwd = os.getcwd()
        except OSError as exc:
            outcome["returncode"] = 1
            outcome["error"] = "the current directory no longer exists: {}: {}".format(type(exc).__name__, exc)
            outcome["workspace_error"] = True
            stderr_sink.write("[pyto-harness] {}\n".format(outcome["error"]))
        if original_cwd is not None:
            try:
                # The in-process path *is* the program's environment: remove the
                # credential-shaped variables for the duration and put them back in a
                # `finally`, so a program that raises cannot strip the harness's own key.
                with temporary_environ_scrub():
                    body()
            finally:
                try:
                    os.chdir(original_cwd)
                except OSError:  # pragma: no cover - the cwd was removed under us
                    pass
        sys.settrace(saved_trace)
        sys.stdout, sys.stderr, sys.argv = saved_stdout, saved_stderr, saved_argv

    worker = threading.Thread(target=run, name="pyto-runpy", daemon=True)
    worker.start()
    worker.join(timeout=timeout + 2.0)
    timed_out = worker.is_alive()
    notes: List[str] = []
    timeout_enforced = bool(outcome.get("tracer_intact", False))
    if outcome.get("timed_out"):
        timeout_enforced = True
        notes.append(
            "The program was stopped cooperatively after {:.0f}s. A program blocked inside a C "
            "call (DNS, socket, a large decode) cannot be interrupted this way; keep programs "
            "short, bounded and non-blocking.".format(timeout)
        )
    elif timed_out:
        timeout_enforced = False
        notes.append(
            "The program was still running after {:.0f}s and could not be interrupted: it is "
            "either blocked in a C call that Python cannot break into or it removed the "
            "cooperative timeout. It keeps running in the background until the app is "
            "suspended.".format(timeout)
        )
        outcome["timed_out"] = True
        outcome["returncode"] = 124
    if not timeout_enforced:
        notes.append(
            "timeout enforced: false - the program disabled the cooperative timeout "
            "(sys.settrace(None)); the {:.0f}s limit did NOT bound it".format(timeout)
        )
    return {
        "mode": "runpy",
        "stdout": stdout_sink.value(),
        "stderr": stderr_sink.value(),
        "returncode": outcome.get("returncode", 1),
        "timed_out": bool(outcome.get("timed_out")),
        "timeout_enforced": timeout_enforced,
        "duration_s": time.monotonic() - started,
        "note": " ".join(notes),
        "capture_path": None,
    }


def _cap(text: str) -> str:
    if len(text) <= RUN_CAPTURE_CHARS:
        return text
    return text[:RUN_CAPTURE_CHARS] + "\n... [{} more characters]".format(len(text) - RUN_CAPTURE_CHARS)


class _ProgramTimeout(BaseException):
    """Raised by the cooperative timeout tracer.

    Derives from ``BaseException`` so that a program's own ``except Exception`` cannot
    swallow its timeout — the same reason ``KeyboardInterrupt`` is not an ``Exception``.
    """


# --------------------------------------------------------------------------------------
# Convenience
# --------------------------------------------------------------------------------------


def default_context(workspace_dir: str, spill_dir: str = "", *, config: Any = None) -> ToolContext:
    """Build the tool context.

    ``config`` is the resolved :class:`harness.config.Config` when the CLI has one; the
    self-repair tools need it (and its path) to run the doctor with the same settings the
    user is running with.  Without it they fall back to a default configuration, so the
    registry is still constructible in a unit test or a preview.
    """
    from . import config as config_module

    workspace = Workspace(workspace_dir)
    resolved_config_path = expand_user_path(config_module.default_config_path(), what="config file path")
    return ToolContext(
        workspace=workspace,
        spill_dir=spill_dir or os.path.join(workspace.root, "tool-output"),
        memory_path=os.path.join(workspace.root, "memory.json"),
        config=config,
        config_path=resolved_config_path,
        state_dir=expand_user_path(config_module.default_state_dir(), what="state directory"),
        harness_root=os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    )


def tool_summary(registry: ToolRegistry) -> List[Tuple[str, str]]:
    """``(name, first line of description)`` for documentation and the UI."""
    return [(tool.name, tool.description.split(". ")[0]) for tool in registry.tools()]
